spring:
  application:
    name: paypal-integration
paypal:
  client-id: AWJLE4ye7uZ2T4vr-oD1wJMohZz1JmgKJckN_vZXwexCSvZ75-3AgRvQWzYdu6PGi5N-w7oz81etnUtQ
  client-secret: EBJoGqZ8dQ7-PTRCIdD_xy1sRK4kwotYlTCSmUVbWxacGKrqgJDI947DCFIegs1XrsbwOwzqUMLl-WIh
  mode: sandbox # use 'sandbox' for testing and 'live' for production