spring:
  application:
    name: paypal-integration
paypal:
  client-id: # https://developer.paypal.com/dashboard from here you can get
  client-secret: # https://developer.paypal.com/dashboard from here you can get
  mode: sandbox # use 'sandbox' for testing and 'live' for production
url:
  success: http://localhost:8080/payment/success
  cansel: http://localhost:8080/payment/cancel